# Индексы, срезы и итеративный обход

https://ru.hexlet.io/courses/python-numpy/lessons/indexing-slicing/theory_unit

Входные данные:

In [2]:
import numpy as np

clicks_values = [
    [319, 265, 319, 328],
    [292, 274, 292, 301],
    [283, 301, 274, 283],
    [328, 364, 328, 319],
    [391, 355, 373, 337],
    [445, 418, 409, 445],
    [481, 400, 481, 409],
    [333, 267, 333, 344],
    [300, 278, 300, 311],
    [289, 311, 278, 289],
    [344, 388, 344, 333],
    [421, 377, 399, 355],
    [487, 454, 443, 487],
    [531, 432, 531, 443],
    [312, 264, 312, 320],
    [288, 272, 288, 296],
    [280, 296, 272, 280],
    [320, 352, 320, 312],
    [376, 344, 360, 328],
    [424, 400, 392, 424],
    [456, 384, 456, 392],
    [347, 269, 347, 360],
    [308, 282, 308, 321],
    [295, 321, 282, 295],
    [360, 412, 360, 347],
    [451, 399, 425, 373],
    [529, 490, 477, 529],
    [581, 464, 581, 477]
]

clicks_values = np.array(clicks_values)
print(clicks_values)

[[319 265 319 328]
 [292 274 292 301]
 [283 301 274 283]
 [328 364 328 319]
 [391 355 373 337]
 [445 418 409 445]
 [481 400 481 409]
 [333 267 333 344]
 [300 278 300 311]
 [289 311 278 289]
 [344 388 344 333]
 [421 377 399 355]
 [487 454 443 487]
 [531 432 531 443]
 [312 264 312 320]
 [288 272 288 296]
 [280 296 272 280]
 [320 352 320 312]
 [376 344 360 328]
 [424 400 392 424]
 [456 384 456 392]
 [347 269 347 360]
 [308 282 308 321]
 [295 321 282 295]
 [360 412 360 347]
 [451 399 425 373]
 [529 490 477 529]
 [581 464 581 477]]


Данные, которые поступают для анализа, могут иметь достаточно большой объем. Чтобы получить подвыборку, аналитик обычно пишет программы и скрипты. Попробуем упростить работу аналитика с помощью правил индексирования массивов Numpy.

Представим, что в работу поступила таблица:

В каждой строке — количество кликов рекламного баннера с четырех площадок
Каждая строка — дни месяца с понедельника по воскресенье
Всего предоставлено четыре недели статистики, то есть в таблице 28 строк. Таблица представлена в виде списка списков целочисленных значений. В руках аналитика оказался Python-интерпретатор с предустановленной библиотекой Numpy. Поможем аналитику найти нужные статистические показатели. Рассмотрим процесс пошагово:

**Шаг 1.** Для работы со списком входных значений необходимо сконвертировать в нужный формат данных. Напишите функцию create_click_numbers_ndarray(clicks_values: np.ndarray), которая возвращает массив numpy.ndarray. Если вы успешно справились с данным заданием в предыдущем уроке, то просто повторите код вашей функции, но убедитесь в корректности ее работы на списке списков.

In [4]:
import numpy as np

clicks_values = [
    [319, 265, 319, 328],
    [292, 274, 292, 301],
    [283, 301, 274, 283],
    [328, 364, 328, 319],
    [391, 355, 373, 337],
    [445, 418, 409, 445],
    [481, 400, 481, 409],
    [333, 267, 333, 344],
    [300, 278, 300, 311],
    [289, 311, 278, 289],
    [344, 388, 344, 333],
    [421, 377, 399, 355],
    [487, 454, 443, 487],
    [531, 432, 531, 443],
    [312, 264, 312, 320],
    [288, 272, 288, 296],
    [280, 296, 272, 280],
    [320, 352, 320, 312],
    [376, 344, 360, 328],
    [424, 400, 392, 424],
    [456, 384, 456, 392],
    [347, 269, 347, 360],
    [308, 282, 308, 321],
    [295, 321, 282, 295],
    [360, 412, 360, 347],
    [451, 399, 425, 373],
    [529, 490, 477, 529],
    [581, 464, 581, 477]
]

clicks_values = np.array(clicks_values)

def create_click_numbers_ndarray(clicks_values: np.ndarray):
    # Ваша функция будет просто возвращать входной массив, так как он уже в нужном формате
    return clicks_values

# Вызываем функцию и сохраняем результат в новую переменную
result = create_click_numbers_ndarray(clicks_values)

# Печатаем результат
print(result)

[[319 265 319 328]
 [292 274 292 301]
 [283 301 274 283]
 [328 364 328 319]
 [391 355 373 337]
 [445 418 409 445]
 [481 400 481 409]
 [333 267 333 344]
 [300 278 300 311]
 [289 311 278 289]
 [344 388 344 333]
 [421 377 399 355]
 [487 454 443 487]
 [531 432 531 443]
 [312 264 312 320]
 [288 272 288 296]
 [280 296 272 280]
 [320 352 320 312]
 [376 344 360 328]
 [424 400 392 424]
 [456 384 456 392]
 [347 269 347 360]
 [308 282 308 321]
 [295 321 282 295]
 [360 412 360 347]
 [451 399 425 373]
 [529 490 477 529]
 [581 464 581 477]]


**Шаг 2.** Напишите функцию get_max_weekly(clicks_values: np.ndarray), которая возвращает список значений [max_in_week_1, max_in_week_2, max_in_week_3, max_in_week_4], где max_in_week_* — максимальное значение кликов в соответствующей неделе. Постарайтесь использовать срезы данных.

In [9]:
import numpy as np

clicks_values = [
    [319, 265, 319, 328],
    [292, 274, 292, 301],
    [283, 301, 274, 283],
    [328, 364, 328, 319],
    [391, 355, 373, 337],
    [445, 418, 409, 445],
    [481, 400, 481, 409],
    [333, 267, 333, 344],
    [300, 278, 300, 311],
    [289, 311, 278, 289],
    [344, 388, 344, 333],
    [421, 377, 399, 355],
    [487, 454, 443, 487],
    [531, 432, 531, 443],
    [312, 264, 312, 320],
    [288, 272, 288, 296],
    [280, 296, 272, 280],
    [320, 352, 320, 312],
    [376, 344, 360, 328],
    [424, 400, 392, 424],
    [456, 384, 456, 392],
    [347, 269, 347, 360],
    [308, 282, 308, 321],
    [295, 321, 282, 295],
    [360, 412, 360, 347],
    [451, 399, 425, 373],
    [529, 490, 477, 529],
    [581, 464, 581, 477]
]

clicks_values = np.array(clicks_values)

def get_max_weekly(clicks_values: np.ndarray):
    # Разбиваем данные на недели с использованием срезов
    week_1 = clicks_values[:7]
    week_2 = clicks_values[7:14]
    week_3 = clicks_values[14:21]
    week_4 = clicks_values[21:28]

    # Находим максимум в каждой неделе с помощью np.max()
    max_in_week_1 = np.max(week_1)
    max_in_week_2 = np.max(week_2)
    max_in_week_3 = np.max(week_3)
    max_in_week_4 = np.max(week_4)
    
    # Возвращаем результат в виде списка
    return [max_in_week_1, max_in_week_2, max_in_week_3, max_in_week_4]

# Вызываем функцию и сохраняем результат в новую переменную
max_weekly_clicks = get_max_weekly(clicks_values)

# Печатаем результат
print(max_weekly_clicks)


[481, 531, 456, 581]


**Шаг 3.** Напишите функцию get_min_weekly(clicks_values: np.ndarray), которая возвращает список значений [min_in_week_1, min_in_week_2, min_in_week_3, min_in_week_4], где min_in_week_* — минимальное значение кликов в соответствующей неделе. Постарайтесь использовать срезы данных.

In [11]:
import numpy as np

clicks_values = [
    [319, 265, 319, 328],
    [292, 274, 292, 301],
    [283, 301, 274, 283],
    [328, 364, 328, 319],
    [391, 355, 373, 337],
    [445, 418, 409, 445],
    [481, 400, 481, 409],
    [333, 267, 333, 344],
    [300, 278, 300, 311],
    [289, 311, 278, 289],
    [344, 388, 344, 333],
    [421, 377, 399, 355],
    [487, 454, 443, 487],
    [531, 432, 531, 443],
    [312, 264, 312, 320],
    [288, 272, 288, 296],
    [280, 296, 272, 280],
    [320, 352, 320, 312],
    [376, 344, 360, 328],
    [424, 400, 392, 424],
    [456, 384, 456, 392],
    [347, 269, 347, 360],
    [308, 282, 308, 321],
    [295, 321, 282, 295],
    [360, 412, 360, 347],
    [451, 399, 425, 373],
    [529, 490, 477, 529],
    [581, 464, 581, 477]
]

clicks_values = np.array(clicks_values)

def get_min_weekly(clicks_values: np.ndarray):
    # Разбиваем данные на недели с использованием срезов
    week_1 = clicks_values[:7]
    week_2 = clicks_values[7:14]
    week_3 = clicks_values[14:21]
    week_4 = clicks_values[21:28]
    
    # Находим минимум в каждой неделе с помощью np.min()
    min_in_week_1 = np.min(week_1)
    min_in_week_2 = np.min(week_2)
    min_in_week_3 = np.min(week_3)
    min_in_week_4 = np.min(week_4)
    
    # Возвращаем результат в виде списка
    return [min_in_week_1, min_in_week_2, min_in_week_3, min_in_week_4]

# Вызываем функцию и сохраняем результат в новую переменную
min_weekly_clicks = get_min_weekly(clicks_values)

# Печатаем результат
print(min_weekly_clicks)

[265, 267, 264, 269]


**Шаг 4.** Напишите функцию get_mean_monday(clicks_values: np.ndarray), которая возвращает среднее значение кликов среди всех точек только в разрезе понедельников. Постарайтесь использовать срезы данных.

In [24]:
import numpy as np

clicks_values = [
    [319, 265, 319, 328],
    [292, 274, 292, 301],
    [283, 301, 274, 283],
    [328, 364, 328, 319],
    [391, 355, 373, 337],
    [445, 418, 409, 445],
    [481, 400, 481, 409],
    [333, 267, 333, 344],
    [300, 278, 300, 311],
    [289, 311, 278, 289],
    [344, 388, 344, 333],
    [421, 377, 399, 355],
    [487, 454, 443, 487],
    [531, 432, 531, 443],
    [312, 264, 312, 320],
    [288, 272, 288, 296],
    [280, 296, 272, 280],
    [320, 352, 320, 312],
    [376, 344, 360, 328],
    [424, 400, 392, 424],
    [456, 384, 456, 392],
    [347, 269, 347, 360],
    [308, 282, 308, 321],
    [295, 321, 282, 295],
    [360, 412, 360, 347],
    [451, 399, 425, 373],
    [529, 490, 477, 529],
    [581, 464, 581, 477]
]

clicks_values = np.array(clicks_values)

def get_mean_monday_all_points(clicks_values: np.ndarray):
    # Используем срез [0::7] для выбора данных по всем точкам и всем понедельникам
    selected_data = clicks_values[0::7]
    # Вычисляем среднее значение для выбранных данных
    mean_value = np.mean(selected_data)
    return mean_value

# Вызываем функцию и выводим результат
mean_value = get_mean_monday_all_points(clicks_values)
print("Среднее значение кликов по всем точкам и всем понедельникам:", mean_value)


Среднее значение кликов по всем точкам и всем понедельникам: 314.9375


**Шаг 5.** Напишите функцию get_max_click(clicks_values: np.ndarray, col_number: int), которая возвращает максимальное значение кликов за весь период для площадки (столбца) под номером col_number. Постарайтесь использовать срезы данных.

In [27]:
import numpy as np

clicks_values = [
    [319, 265, 319, 328],
    [292, 274, 292, 301],
    [283, 301, 274, 283],
    [328, 364, 328, 319],
    [391, 355, 373, 337],
    [445, 418, 409, 445],
    [481, 400, 481, 409],
    [333, 267, 333, 344],
    [300, 278, 300, 311],
    [289, 311, 278, 289],
    [344, 388, 344, 333],
    [421, 377, 399, 355],
    [487, 454, 443, 487],
    [531, 432, 531, 443],
    [312, 264, 312, 320],
    [288, 272, 288, 296],
    [280, 296, 272, 280],
    [320, 352, 320, 312],
    [376, 344, 360, 328],
    [424, 400, 392, 424],
    [456, 384, 456, 392],
    [347, 269, 347, 360],
    [308, 282, 308, 321],
    [295, 321, 282, 295],
    [360, 412, 360, 347],
    [451, 399, 425, 373],
    [529, 490, 477, 529],
    [581, 464, 581, 477]
]

clicks_values = np.array(clicks_values)

def get_max_click(clicks_values: np.ndarray, col_number: int):
    col_data = clicks_values[:, col_number]
    max_click = np.max(col_data)
    return max_click

# Пройдемся циклом по всем столбцам и выведем максимальное значение для каждого
for col_number in range(clicks_values.shape[1]):
    max_click_value = get_max_click(clicks_values, col_number)
    print(f"Максимальное значение в столбце {col_number}: {max_click_value}")


Максимальное значение в столбце 0: 581
Максимальное значение в столбце 1: 490
Максимальное значение в столбце 2: 581
Максимальное значение в столбце 3: 529
